//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class participante_deporte_rutina
    {
        public int id { get; set; }
        public int participante_id { get; set; }
        public int deporte_id { get; set; }
        public int rutina_id { get; set; }
    
        public virtual deporte deporte { get; set; }
        public virtual participante participante { get; set; }
        public virtual rutina rutina { get; set; }
    }
}
