//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutinas_deportes
    {
        public int id { get; set; }
        public Nullable<int> rutina_id { get; set; }
        public Nullable<int> sport_id { get; set; }
    
        public virtual deporte deporte { get; set; }
        public virtual rutina rutina { get; set; }
    }
}
