//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_View.ServicioRutina {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioRutina.IRutinas")]
    public interface IRutinas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/CrearRutina", ReplyAction="http://tempuri.org/IRutinas/CrearRutinaResponse")]
        bool CrearRutina(AccesoDatos.Modelo.rutina Rutinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/CrearRutina", ReplyAction="http://tempuri.org/IRutinas/CrearRutinaResponse")]
        System.Threading.Tasks.Task<bool> CrearRutinaAsync(AccesoDatos.Modelo.rutina Rutinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/EditarRutina", ReplyAction="http://tempuri.org/IRutinas/EditarRutinaResponse")]
        bool EditarRutina(AccesoDatos.Modelo.rutina oRutinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/EditarRutina", ReplyAction="http://tempuri.org/IRutinas/EditarRutinaResponse")]
        System.Threading.Tasks.Task<bool> EditarRutinaAsync(AccesoDatos.Modelo.rutina oRutinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/EliminarRutina", ReplyAction="http://tempuri.org/IRutinas/EliminarRutinaResponse")]
        bool EliminarRutina(AccesoDatos.Modelo.rutina oRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/EliminarRutina", ReplyAction="http://tempuri.org/IRutinas/EliminarRutinaResponse")]
        System.Threading.Tasks.Task<bool> EliminarRutinaAsync(AccesoDatos.Modelo.rutina oRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/ChargerRutinas", ReplyAction="http://tempuri.org/IRutinas/ChargerRutinasResponse")]
        AccesoDatos.Rutina[] ChargerRutinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/ChargerRutinas", ReplyAction="http://tempuri.org/IRutinas/ChargerRutinasResponse")]
        System.Threading.Tasks.Task<AccesoDatos.Rutina[]> ChargerRutinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/CreateMultiRelation", ReplyAction="http://tempuri.org/IRutinas/CreateMultiRelationResponse")]
        bool CreateMultiRelation(AccesoDatos.Modelo.participante_deporte_rutina oRelation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/CreateMultiRelation", ReplyAction="http://tempuri.org/IRutinas/CreateMultiRelationResponse")]
        System.Threading.Tasks.Task<bool> CreateMultiRelationAsync(AccesoDatos.Modelo.participante_deporte_rutina oRelation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/CreateRelation", ReplyAction="http://tempuri.org/IRutinas/CreateRelationResponse")]
        bool CreateRelation(AccesoDatos.Modelo.rutinas_deportes oRelational);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRutinas/CreateRelation", ReplyAction="http://tempuri.org/IRutinas/CreateRelationResponse")]
        System.Threading.Tasks.Task<bool> CreateRelationAsync(AccesoDatos.Modelo.rutinas_deportes oRelational);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRutinasChannel : Project_View.ServicioRutina.IRutinas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RutinasClient : System.ServiceModel.ClientBase<Project_View.ServicioRutina.IRutinas>, Project_View.ServicioRutina.IRutinas {
        
        public RutinasClient() {
        }
        
        public RutinasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RutinasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RutinasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RutinasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CrearRutina(AccesoDatos.Modelo.rutina Rutinas) {
            return base.Channel.CrearRutina(Rutinas);
        }
        
        public System.Threading.Tasks.Task<bool> CrearRutinaAsync(AccesoDatos.Modelo.rutina Rutinas) {
            return base.Channel.CrearRutinaAsync(Rutinas);
        }
        
        public bool EditarRutina(AccesoDatos.Modelo.rutina oRutinas) {
            return base.Channel.EditarRutina(oRutinas);
        }
        
        public System.Threading.Tasks.Task<bool> EditarRutinaAsync(AccesoDatos.Modelo.rutina oRutinas) {
            return base.Channel.EditarRutinaAsync(oRutinas);
        }
        
        public bool EliminarRutina(AccesoDatos.Modelo.rutina oRutina) {
            return base.Channel.EliminarRutina(oRutina);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarRutinaAsync(AccesoDatos.Modelo.rutina oRutina) {
            return base.Channel.EliminarRutinaAsync(oRutina);
        }
        
        public AccesoDatos.Rutina[] ChargerRutinas() {
            return base.Channel.ChargerRutinas();
        }
        
        public System.Threading.Tasks.Task<AccesoDatos.Rutina[]> ChargerRutinasAsync() {
            return base.Channel.ChargerRutinasAsync();
        }
        
        public bool CreateMultiRelation(AccesoDatos.Modelo.participante_deporte_rutina oRelation) {
            return base.Channel.CreateMultiRelation(oRelation);
        }
        
        public System.Threading.Tasks.Task<bool> CreateMultiRelationAsync(AccesoDatos.Modelo.participante_deporte_rutina oRelation) {
            return base.Channel.CreateMultiRelationAsync(oRelation);
        }
        
        public bool CreateRelation(AccesoDatos.Modelo.rutinas_deportes oRelational) {
            return base.Channel.CreateRelation(oRelational);
        }
        
        public System.Threading.Tasks.Task<bool> CreateRelationAsync(AccesoDatos.Modelo.rutinas_deportes oRelational) {
            return base.Channel.CreateRelationAsync(oRelational);
        }
    }
}
