//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class deporte
    {
        public deporte()
        {
            this.participante_deporte_rutina = new HashSet<participante_deporte_rutina>();
            this.rutinas_deportes = new HashSet<rutinas_deportes>();
        }
    
        public int id { get; set; }
        public string Deporte1 { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<participante_deporte_rutina> participante_deporte_rutina { get; set; }
        public virtual ICollection<rutinas_deportes> rutinas_deportes { get; set; }
    }
}
