//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class participante
    {
        public participante()
        {
            this.participante_deporte_rutina = new HashSet<participante_deporte_rutina>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Fecha_Ingreso { get; set; }
    
        public virtual ICollection<participante_deporte_rutina> participante_deporte_rutina { get; set; }
    }
}
