//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UTN_SPORTS_ModelContainer : DbContext
    {
        public UTN_SPORTS_ModelContainer()
            : base("name=UTN_SPORTS_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<deporte> deportes { get; set; }
        public DbSet<participante> participantes { get; set; }
        public DbSet<participante_deporte_rutina> participante_deporte_rutina { get; set; }
        public DbSet<rutina> rutinas { get; set; }
        public DbSet<rutinas_deportes> rutinas_deportes { get; set; }
        public DbSet<user> users { get; set; }
    }
}
