//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18010
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_View.ServicioUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuario.IUsuariosWebService")]
    public interface IUsuariosWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosWebService/VerifyUsers", ReplyAction="http://tempuri.org/IUsuariosWebService/VerifyUsersResponse")]
        int VerifyUsers(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosWebService/VerifyUsers", ReplyAction="http://tempuri.org/IUsuariosWebService/VerifyUsersResponse")]
        System.Threading.Tasks.Task<int> VerifyUsersAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosWebService/NewUser", ReplyAction="http://tempuri.org/IUsuariosWebService/NewUserResponse")]
        bool NewUser(AccesoDatos.Modelo.user oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosWebService/NewUser", ReplyAction="http://tempuri.org/IUsuariosWebService/NewUserResponse")]
        System.Threading.Tasks.Task<bool> NewUserAsync(AccesoDatos.Modelo.user oUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosWebServiceChannel : Project_View.ServicioUsuario.IUsuariosWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosWebServiceClient : System.ServiceModel.ClientBase<Project_View.ServicioUsuario.IUsuariosWebService>, Project_View.ServicioUsuario.IUsuariosWebService {
        
        public UsuariosWebServiceClient() {
        }
        
        public UsuariosWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int VerifyUsers(string username, string password) {
            return base.Channel.VerifyUsers(username, password);
        }
        
        public System.Threading.Tasks.Task<int> VerifyUsersAsync(string username, string password) {
            return base.Channel.VerifyUsersAsync(username, password);
        }
        
        public bool NewUser(AccesoDatos.Modelo.user oUser) {
            return base.Channel.NewUser(oUser);
        }
        
        public System.Threading.Tasks.Task<bool> NewUserAsync(AccesoDatos.Modelo.user oUser) {
            return base.Channel.NewUserAsync(oUser);
        }
    }
}
